rvm:
  - "2.2.5"
  - "2.3.0"
  - "2.3.1"
  - "2.4.2"
  - "2.5.0-preview1"
addons:
  code_climate:
    repo_token: 397c19af63ca3467cff6fd640b0460b691f687118332b5989f530d28f82adcb8
notifications:
  slack: my-codeworks:fwKO4YfipnmNKJQL3cRSEoKB
  email: false
